### ISSUE TITLE
ACL issue with sasl

### ISSUE THREAD

**Issue by simplesteph** [elkozmon/zoonavigator#1]
Some of my nodes are configured with sasl access. It seems that the API isn't configured to work with those:

```
zoonavigator-api | [debug] c.e.z.c.c.b.DefaultBackgroundPromiseFactory - GET_ACL event completed with result code 0
zoonavigator-api | [error] o.a.c.f.i.CuratorFrameworkImpl - Background operation result handling threw exception
zoonavigator-api | scala.MatchError: sasl (of class java.lang.String)
zoonavigator-api | 	at com.elkozmon.zoonavigator.core.zookeeper.acl.Scheme$.fromZookeeperScheme(Scheme.scala:40)
zoonavigator-api | 	at com.elkozmon.zoonavigator.core.query.queries.GetZNodeAclQueryHandler$$anonfun$2$$anonfun$3.apply(GetZNodeAclQueryHandler.scala:51)
zoonavigator-api | 	at com.elkozmon.zoonavigator.core.query.queries.GetZNodeAclQueryHandler$$anonfun$2$$anonfun$3.apply(GetZNodeAclQueryHandler.scala:48)
zoonavigator-api | 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
zoonavigator-api | 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
zoonavigator-api | 	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
zoonavigator-api | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
zoonavigator-api | 	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
zoonavigator-api | 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
zoonavigator-api | 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
zoonavigator-api | [warn] application - Background operation result handling threw exception
zoonavigator-api | scala.MatchError: sasl (of class java.lang.String)
zoonavigator-api | 	at com.elkozmon.zoonavigator.core.zookeeper.acl.Scheme$.fromZookeeperScheme(Scheme.scala:40)
zoonavigator-api | 	at com.elkozmon.zoonavigator.core.query.queries.GetZNodeAclQueryHandler$$anonfun$2$$anonfun$3.apply(GetZNodeAclQueryHandler.scala:51)
zoonavigator-api | 	at com.elkozmon.zoonavigator.core.query.queries.GetZNodeAclQueryHandler$$anonfun$2$$anonfun$3.apply(GetZNodeAclQueryHandler.scala:48)
zoonavigator-api | 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
zoonavigator-api | 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
zoonavigator-api | 	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
zoonavigator-api | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
zoonavigator-api | 	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
zoonavigator-api | 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
zoonavigator-api | 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
zoonavigator-api | [debug] application - Closing connection to zookeeper-1.zk.dev.analytics.in.cld:2181. Cause: EXPIRED
```

**Comment by elkozmon** [comment]
Indeed, sasl is not supported at the moment. 
It shouldn't be too much work though, I will look into it this week.

**Comment by elkozmon** [comment]
API should be able to handle any ACL scheme now.
Docker images with the fix are now available under version tag 0.2.0.
Please let me know if it didn't solve the issue for you!

**Comment by simplesteph** [comment]
@elkozmon thanks will test and get back to you!

**Comment by simplesteph** [comment]
@elkozmon working like a charm, thanks!

**Comment by elkozmon** [comment]
@simplesteph good! thanks to you, too :)
