### ISSUE TITLE
Make connection to ZK with SSL failed 

### ISSUE THREAD

**Issue by tommy04062019** [elkozmon/zoonavigator#76]
Run app with Docker:
```
docker run \
  -d --network host \
  --mount type=bind,source=/root/navigator,target=/ssl \
  -e HTTP_PORT=9000 \
  -e ZK_SASL_CLIENT=false \
  -e ZK_CLIENT_SECURE=true \
  -e ZK_SSL_KEYSTORE_PATH=/ssl/zookeeper.keystore.jks \
  -e ZK_SSL_KEYSTORE_PASSWORD=pass \
  -e ZK_SSL_TRUSTSTORE_PATH=/ssl/zookeeper.truststore.jks \
  -e ZK_SSL_TRUSTSTORE_PASSWORD=pass \
  --name zoonavigator \
  --restart unless-stopped \
  elkozmon/zoonavigator:latest
```

Error:
```
Caused by: java.security.cert.CertificateException: Failed to verify both host address and host name
	at org.apache.zookeeper.common.ZKTrustManager.performHostVerification(ZKTrustManager.java:145)
	at org.apache.zookeeper.common.ZKTrustManager.checkServerTrusted(ZKTrustManager.java:104)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:632)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1074)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Certificate for <xxx.xxx.xxx> doesn't match any of the subject alternative names: [xxx.xxx.xxx.xxx, __omit_place_holder__54db00186e0cdad8aee31ba91a3172d382b46f01]
```
Expected results:
The certs is self-signed, and it would be accepted  by igrnore verify ssl.

**Comment by elkozmon** [comment]
Hi, sorry for the late reply.

Sadly, ZooNavigator still runs on ZK client version `3.4.11` which AFAIK does not have the option to disable hostname verification. 
[ZK docs](https://zookeeper.apache.org/doc/r3.5.5/zookeeperAdmin.html) suggest it has been added in version `3.5.5` (lookup `zookeeper.ssl.hostnameVerification`).

Right now I'm waiting for my [main dependency to upgrade to ZK 3.7](https://github.com/apache/curator/pull/385) and when that happens I will definitely add support to disable hostname verification.
