### ISSUE TITLE
How to upload and download large files

### ISSUE THREAD

**Issue by gmchenyong** [elkozmon/zoonavigator#88]
There are several nodes on zookeeper that are larger than 2M. Jute.maxbuffer can be configured on zk. Does zoonavigator need to be configured?

**Comment by gmchenyong** [comment]
java.io.IOException: Unreasonable length = 1972502
        at org.apache.jute.BinaryInputArchive.checkLength(BinaryInputArchive.java:127)
        at org.apache.jute.BinaryInputArchive.readBuffer(BinaryInputArchive.java:92)
        at org.apache.zookeeper.proto.GetDataResponse.deserialize(GetDataResponse.java:56)
        at org.apache.zookeeper.ClientCnxn$SendThread.readResponse(ClientCnxn.java:840)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:94)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)
When jute.maxbuffer in the client side is less than the server side, the client wants to read the data exceeds jute.maxbuffer in the client side, the client side will get java.io.IOException: Unreasonable length or Packet len is out of range!
